In [125]:
import pandas as pd
import numpy as np

Fintrust = pd.read_csv('transactionfintrust.csv')
#fintrust transaction data 

Trustfin = pd.read_csv('Customerfintrust.csv')

Fintrust

,Transaction_ID,Customer_ID,Transaction_DateTime,Transaction_Type,Amount_NGN,Channel,Device_Type,Location,International_Transaction,Transaction_Status,Risk_Review_Flag
0,FT-T000001,FT-C01135,01/01/2026 00:00,Card Purchase,5923.80,Mobile App,Android,Enugu,No,Reversed,Yes
1,FT-T000002,FT-C00428,01/01/2026 00:10,Cash Withdrawal,11681.12,ATM,Android,Kaduna,No,Successful,Yes
2,FT-T000003,FT-C00469,01/01/2026 00:21,Transfer,571.91,ATM,POS Terminal,Kano,No,Successful,No
3,FT-T000004,FT-C01015,01/01/2026 00:32,Deposit,105367.52,Mobile App,Web Browser,Abuja,No,Successful,No
4,FT-T000005,FT-C00870,01/01/2026 00:43,Cash Withdrawal,3049.06,Mobile App,POS Terminal,Abuja,No,Successful,No
...,...,...,...,...,...,...,...,...,...,...,...
11995,FT-T011996,FT-C01367,3/31/2026 23:16,Card Purchase,9336.19,Web,Web Browser,Lagos,No,Successful,No
11996,FT-T011997,FT-C00395,3/31/2026 23:27,Airtime/Data,16198.02,Mobile App,iOS,Ibadan,No,Successful,No
11997,FT-T011998,FT-C00484,3/31/2026 23:38,Card Purchase,62448.87,Mobile App,ATM Terminal,Lagos,No,Successful,No
11998,FT-T011999,FT-C00666,3/31/2026 23:49,Card Purchase,696.48,Mobile App,Android,Benin City,No,Successful,No
11999,FT-T012000,FT-C00456,3/31/2026 23:59,Cash Withdrawal,26888.41,POS,iOS,Kaduna,No,Successful,Yes

In [17]:
Fintrust.shape

(12000, 11)

In [86]:
Fintrust.info

<bound method DataFrame.info of       Transaction_ID Customer_ID Transaction_DateTime Transaction_Type  \
0         FT-T000001   FT-C01135     01/01/2026 00:00    Card Purchase
1         FT-T000002   FT-C00428     01/01/2026 00:10  Cash Withdrawal
2         FT-T000003   FT-C00469     01/01/2026 00:21         Transfer
3         FT-T000004   FT-C01015     01/01/2026 00:32          Deposit
4         FT-T000005   FT-C00870     01/01/2026 00:43  Cash Withdrawal
...              ...         ...                  ...              ...
11995     FT-T011996   FT-C01367      3/31/2026 23:16    Card Purchase
11996     FT-T011997   FT-C00395      3/31/2026 23:27     Airtime/Data
11997     FT-T011998   FT-C00484      3/31/2026 23:38    Card Purchase
11998     FT-T011999   FT-C00666      3/31/2026 23:49    Card Purchase
11999     FT-T012000   FT-C00456      3/31/2026 23:59  Cash Withdrawal

       Amount_NGN     Channel   Device_Type    Location  \
0         5923.80  Mobile App       Android       Enugu
1        11681.12         ATM       Android      Kaduna
2          571.91         ATM  POS Terminal        Kano
3       105367.52  Mobile App   Web Browser       Abuja
4         3049.06  Mobile App  POS Terminal       Abuja
...           ...         ...           ...         ...
11995     9336.19         Web   Web Browser       Lagos
11996    16198.02  Mobile App           iOS      Ibadan
11997    62448.87  Mobile App  ATM Terminal       Lagos
11998      696.48  Mobile App       Android  Benin City
11999    26888.41         POS           iOS      Kaduna

      International_Transaction Transaction_Status Risk_Review_Flag
0                            No           Reversed              Yes
1                            No         Successful              Yes
2                            No         Successful               No
3                            No         Successful               No
4                            No         Successful               No
...                         ...                ...              ...
11995                        No         Successful               No
11996                        No         Successful               No
11997                        No         Successful               No
11998                        No         Successful               No
11999                        No         Successful              Yes

[12000 rows x 11 columns]>

In [87]:
Fintrust.dtypes

Transaction_ID                   str
Customer_ID                      str
Transaction_DateTime             str
Transaction_Type                 str
Amount_NGN                   float64
Channel                          str
Device_Type                      str
Location                         str
International_Transaction        str
Transaction_Status               str
Risk_Review_Flag                 str
dtype: object

In [27]:
Fintrust.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_DateTime',
       'Transaction_Type', 'Amount_NGN', 'Channel', 'Device_Type', 'Location',
       'International_Transaction', 'Transaction_Status', 'Risk_Review_Flag'],
      dtype='str')

In [137]:
Fintrust['Transaction_Type'].value_counts()

Transaction_Type
Transfer           3549
Card Purchase      3033
Bill Payment       1475
Cash Withdrawal    1430
Deposit            1328
Airtime/Data       1185
Name: count, dtype: int64

In [136]:
Fintrust['Device_Type'].value_counts()

Device_Type
Android         4797
iOS             2920
POS Terminal    1571
Web Browser     1447
ATM Terminal    1169
Name: count, dtype: int64

In [135]:
Fintrust['Channel'].value_counts()

Channel
Mobile App    5102
POS           2393
Web           1869
ATM           1747
USSD           889
Name: count, dtype: int64

In [134]:
Fintrust['Location'].value_counts()

Location
Ibadan           1550
Kano             1526
Port Harcourt    1520
Enugu            1484
Kaduna           1481
Abuja            1461
Benin City       1451
Lagos            1431
Name: count, dtype: int64

In [53]:
((Fintrust['Risk_Review_Flag']=='Yes') & (Fintrust['Transaction_Type']== 'Bill Payment')).sum()

np.int64(189)

In [21]:
((Fintrust['Risk_Review_Flag']=='Yes') & (Fintrust['International_Transaction']== 'Yes')).sum()

np.int64(177)

In [59]:
((Fintrust['Risk_Review_Flag']=='Yes') & (Fintrust['Channel']== 'Mobile App')).sum()

np.int64(990)

In [61]:
((Fintrust['Risk_Review_Flag']=='Yes') & (Fintrust['Location']== 'Lagos')).sum()

np.int64(279)

In [65]:
((Fintrust['Risk_Review_Flag']=='Yes') & (Fintrust['Device_Type']== 'iOS')).sum()

np.int64(540)

In [48]:
pd.isnull(Fintrust).sum()

Transaction_ID                0
Customer_ID                   0
Transaction_DateTime          0
Transaction_Type              0
Amount_NGN                    0
Channel                       0
Device_Type                  96
Location                     96
International_Transaction     0
Transaction_Status            0
Risk_Review_Flag              0
dtype: int64

In [77]:
Trustfin

,Customer_ID,Customer_Name,Age,Gender,City,Customer_Segment,Account_Type,Tenure_Months,Digital_Engagement_Score,Monthly_Income_Band,Preferred_Channel,Account_Status
0,FT-C00001,Ibrahim Adeyemi,56,Male,Lagos,Premium,Savings,55,84.9,500k-999k,Mobile App,Active
1,FT-C00002,Yusuf Mohammed,46,Male,Kano,Everyday,Current,79,50.7,500k-999k,Mobile App,Active
2,FT-C00003,Emeka Adeyemi,32,Female,Port Harcourt,Everyday,Savings,43,56.1,1m+,Mobile App,Active
3,FT-C00004,David Williams,60,Female,Benin City,Premium,Premium,44,54.0,500k-999k,Mobile App,Dormant
4,FT-C00005,Blessing Adeyemi,25,Male,Kaduna,Premium,Savings,68,85.1,500k-999k,Mobile App,Active
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,FT-C01496,Grace Adeyemi,24,Male,Lagos,Everyday,Savings,35,76.0,250k-499k,Mobile App,Active
1496,FT-C01497,Zainab Adebayo,26,Male,Ibadan,Premium,Current,72,63.2,100k-249k,Mobile App,Active
1497,FT-C01498,Tunde Ojo,65,Male,Enugu,Student,Savings,66,93.1,250k-499k,Mobile App,Active
1498,FT-C01499,Samuel Adebayo,25,Male,Benin City,Everyday,Premium,6,88.8,100k-249k,Mobile App,Active
1499,FT-C01500,Blessing Adebayo,40,Male,Lagos,Student,Current,31,51.1,100k-249k,Web,Active

In [82]:
Trustfin.shape

(1500, 12)

In [83]:
Trustfin.describe

<bound method NDFrame.describe of      Customer_ID     Customer_Name  Age  Gender           City  \
0      FT-C00001   Ibrahim Adeyemi   56    Male          Lagos
1      FT-C00002    Yusuf Mohammed   46    Male           Kano
2      FT-C00003     Emeka Adeyemi   32  Female  Port Harcourt
3      FT-C00004    David Williams   60  Female     Benin City
4      FT-C00005  Blessing Adeyemi   25    Male         Kaduna
...          ...               ...  ...     ...            ...
1495   FT-C01496     Grace Adeyemi   24    Male          Lagos
1496   FT-C01497    Zainab Adebayo   26    Male         Ibadan
1497   FT-C01498         Tunde Ojo   65    Male          Enugu
1498   FT-C01499    Samuel Adebayo   25    Male     Benin City
1499   FT-C01500  Blessing Adebayo   40    Male          Lagos

     Customer_Segment Account_Type  Tenure_Months  Digital_Engagement_Score  \
0             Premium      Savings             55                      84.9
1            Everyday      Current             79                      50.7
2            Everyday      Savings             43                      56.1
3             Premium      Premium             44                      54.0
4             Premium      Savings             68                      85.1
...               ...          ...            ...                       ...
1495         Everyday      Savings             35                      76.0
1496          Premium      Current             72                      63.2
1497          Student      Savings             66                      93.1
1498         Everyday      Premium              6                      88.8
1499          Student      Current             31                      51.1

     Monthly_Income_Band Preferred_Channel Account_Status
0              500k-999k        Mobile App         Active
1              500k-999k        Mobile App         Active
2                    1m+        Mobile App         Active
3              500k-999k        Mobile App        Dormant
4              500k-999k        Mobile App         Active
...                  ...               ...            ...
1495           250k-499k        Mobile App         Active
1496           100k-249k        Mobile App         Active
1497           250k-499k        Mobile App         Active
1498           100k-249k        Mobile App         Active
1499           100k-249k               Web         Active

[1500 rows x 12 columns]>

In [85]:
Trustfin.dtypes

Customer_ID                     str
Customer_Name                   str
Age                           int64
Gender                          str
City                            str
Customer_Segment                str
Account_Type                    str
Tenure_Months                 int64
Digital_Engagement_Score    float64
Monthly_Income_Band             str
Preferred_Channel               str
Account_Status                  str
dtype: object

In [91]:
pd.isnull(Trustfin).sum()

Customer_ID                 0
Customer_Name               0
Age                         0
Gender                      0
City                        0
Customer_Segment            0
Account_Type                0
Tenure_Months               0
Digital_Engagement_Score    0
Monthly_Income_Band         0
Preferred_Channel           0
Account_Status              0
dtype: int64

In [81]:
Trustfin.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City',
       'Customer_Segment', 'Account_Type', 'Tenure_Months',
       'Digital_Engagement_Score', 'Monthly_Income_Band', 'Preferred_Channel',
       'Account_Status'],
      dtype='str')

In [133]:
(Trustfin['Customer_Segment']).value_counts()

Customer_Segment
Everyday    711
Premium     295
Student     278
SME         216
Name: count, dtype: int64

In [130]:
(Trustfin['Account_Type']).value_counts()

Account_Type
Savings    893
Current    378
Premium    229
Name: count, dtype: int64

In [131]:
(Trustfin['Monthly_Income_Band']).value_counts()

Monthly_Income_Band
100k-249k     430
250k-499k     416
Below 100k    265
500k-999k     255
1m+           134
Name: count, dtype: int64

In [132]:
(Trustfin['Preferred_Channel']).value_counts()

Preferred_Channel
Mobile App    924
Web           357
USSD          219
Name: count, dtype: int64

In [95]:
(Trustfin['Age']).max()

np.int64(65)

In [110]:
(Fintrust['Amount_NGN']).sum()

np.float64(560477354.85)

In [148]:
filt_data = Fintrust[(Fintrust['Transaction_Type'] == 'Card Purchase') & (Fintrust['Risk_Review_Flag']=='No')]

In [149]:
total_fin = filt_data['Amount_NGN'].sum()
total_fin

np.float64(72432592.33999999)

In [170]:
Trustfin[Trustfin['Tenure_Months'] >= 50]

,Customer_ID,Customer_Name,Age,Gender,City,Customer_Segment,Account_Type,Tenure_Months,Digital_Engagement_Score,Monthly_Income_Band,Preferred_Channel,Account_Status
0,FT-C00001,Ibrahim Adeyemi,56,Male,Lagos,Premium,Savings,55,84.9,500k-999k,Mobile App,Active
1,FT-C00002,Yusuf Mohammed,46,Male,Kano,Everyday,Current,79,50.7,500k-999k,Mobile App,Active
4,FT-C00005,Blessing Adeyemi,25,Male,Kaduna,Premium,Savings,68,85.1,500k-999k,Mobile App,Active
10,FT-C00011,Chiamaka Bello,28,Male,Abuja,Premium,Savings,75,70.7,Below 100k,Web,Dormant
12,FT-C00013,Ada Mohammed,53,Female,Lagos,Everyday,Savings,62,90.4,100k-249k,Mobile App,Dormant
...,...,...,...,...,...,...,...,...,...,...,...,...
1484,FT-C01485,Mariam Ibrahim,27,Female,Lagos,Everyday,Current,52,77.6,100k-249k,Web,Active
1488,FT-C01489,Blessing Eze,40,Female,Benin City,Everyday,Current,88,48.8,250k-499k,Web,Restricted
1492,FT-C01493,Daniel Adebayo,24,Male,Lagos,SME,Premium,78,81.4,500k-999k,Mobile App,Active
1496,FT-C01497,Zainab Adebayo,26,Male,Ibadan,Premium,Current,72,63.2,100k-249k,Mobile App,Active
1497,FT-C01498,Tunde Ojo,65,Male,Enugu,Student,Savings,66,93.1,250k-499k,Mobile App,Active

In [168]:
Fintrust[(Fintrust['Transaction_Type'] == 'Bill Payment') ]

,Transaction_ID,Customer_ID,Transaction_DateTime,Transaction_Type,Amount_NGN,Channel,Device_Type,Location,International_Transaction,Transaction_Status,Risk_Review_Flag
12,FT-T000013,FT-C00587,01/01/2026 02:09,Bill Payment,717.93,Web,iOS,Enugu,No,Successful,No
19,FT-T000020,FT-C01233,01/01/2026 03:25,Bill Payment,523.76,Mobile App,iOS,Kano,No,Successful,No
21,FT-T000022,FT-C00555,01/01/2026 03:46,Bill Payment,45562.37,POS,Android,Abuja,No,Successful,No
22,FT-T000023,FT-C00107,01/01/2026 03:57,Bill Payment,1683.22,USSD,Web Browser,Enugu,No,Successful,No
27,FT-T000028,FT-C01246,01/01/2026 04:51,Bill Payment,3475.92,Web,POS Terminal,Ibadan,No,Successful,No
...,...,...,...,...,...,...,...,...,...,...,...
11957,FT-T011958,FT-C00778,3/31/2026 16:26,Bill Payment,7755.26,ATM,ATM Terminal,Port Harcourt,No,Successful,No
11958,FT-T011959,FT-C01334,3/31/2026 16:37,Bill Payment,22779.06,POS,POS Terminal,Kano,No,Successful,No
11985,FT-T011986,FT-C00889,3/31/2026 21:28,Bill Payment,8064.06,Web,POS Terminal,Abuja,No,Successful,No
11990,FT-T011991,FT-C01150,3/31/2026 22:22,Bill Payment,73992.29,POS,ATM Terminal,Kaduna,No,Successful,Yes
11993,FT-T011994,FT-C00707,3/31/2026 22:55,Bill Payment,7767.84,Mobile App,iOS,Kano,Yes,Successful,No